auth-server: http://localhost:8080 # 认证服务器地址

server:
  port: 8085
security:
  oauth2:
    client:
      client-id: code_client
      client-secret: code_client
      scope: user_info
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
      authorized-grant-types: authorization_code,password,refresh_token
    resource:
      token-info-uri: ${auth-server}/oauth/check_token
      